"""Add project_id and organization_id to job table

Revision ID: 043
Revises: 042
Create Date: 2026-02-04 14:39:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "043"
down_revision = "042"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add organization_id column
    op.add_column(
        "job",
        sa.Column(
            "organization_id",
            sa.Integer(),
            nullable=False,
            comment="Reference to the organization",
        ),
    )
    
    # Add project_id column
    op.add_column(
        "job",
        sa.Column(
            "project_id",
            sa.Integer(),
            nullable=False,
            comment="Reference to the project",
        ),
    )
    
    # Create foreign key constraints
    op.create_foreign_key(
        "fk_job_organization_id",
        "job",
        "organization",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    
    op.create_foreign_key(
        "fk_job_project_id",
        "job",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    
    # Create indexes
    op.create_index(
        "ix_job_organization_id",
        "job",
        ["organization_id"],
        unique=False,
    )
    
    op.create_index(
        "ix_job_project_id",
        "job",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index("ix_job_project_id", table_name="job")
    op.drop_index("ix_job_organization_id", table_name="job")
    
    # Drop foreign key constraints
    op.drop_constraint("fk_job_project_id", "job", type_="foreignkey")
    op.drop_constraint("fk_job_organization_id", "job", type_="foreignkey")
    
    # Drop columns
    op.drop_column("job", "project_id")
    op.drop_column("job", "organization_id")
    # ### end Alembic commands ###
